### ISSUE TITLE
[FEATURE] 그리드 보기 - 구독하기 / 해지하기

### ISSUE THREAD

**Issue by ori5r2** [ori5r2/fe-newsstand#1]
## Description
그리드 보기 (전체 언론사 보기)에서 구독하기 및 해지하기 버튼 기능

## Todo
- [x] 전체 언론사 탭, 내가 구독한 언론사 탭 기능
- [x] 그리드 뷰 (전체 언론사 / 내가 구독한 언론사) UI
- [x] 그리드 셀 hover : 구독하기 버튼 나타남 (아직 구독하지 않은 경우)
- [x] 그리드 셀 hover : 해지하기 버튼 나타남 (이미 구독한 경우)
- [x] 구독하기 버튼 click1 : 스낵바 5초 유지
- [x] 구독하기 버튼 click2 : 스낵바 사라지고 내가 구독한 언론사로 넘어감
- [x] 해지하기 버튼 click1 : 구독해지 알림
- [x] 해지하기 버튼 click2 : 구독해지 알림 버튼 클릭 시 해지 후 이벤트
- [x] 구독한 언론사 저장하는 객체 만들기

## ETC
**Observer패턴을 활용하여 구독한 언론사를 저장하는 객체를 만들고 관리함**

1 . Subject class 생성하여 관찰자 등록/해지하는 틀을 만든다.
```
class Subject {
    constructor() {
        this._observers = [];
        this._state = [];
    }

    subscribe(observer) {
        this._observers.push(observer);
    }

    unsubscribe(observer) {
        this._observers = this._observers.filter((obs) => obs !== observer);
    }
}
```

2. Subject class를 상속받아서 받아서 구독한 언론사의 상태 변경 및 관리하는 함수를 생성한다.
```
class subscribeSubject extends Subject {
    addState(press_idx) {
        this._state.push(press_idx);
        this.notifyAll();
    }

    deleteState(press_idx) {
        this._state = this._state.filter((idx) => idx !== press_idx);
        this.notifyAll();
    }

    getIdx() {
        return this._state;
    }

    notifyAll(isAdd) {
        this._observers.forEach((sbs) => {
            try {
                sbs.update(this._state);
            } catch (err) {
                console.error("observer error", err);
            }
        });
    }
}

const _sub_press_list = new subscribeSubject();
```

3. 전체 언론사 그리드뷰, 내가 구독한 언론사 그리드뷰를 생성하여 상태 변경할 경우 실행하는 함수를 작성한다.
```
// grid view page 정보 - 전체 언론사 (관찰자)
class gridViewEntire extends gridViewInfo {
    // 구독한 언론사 리스트가 변경될 경우 뷰 업데이트
    update = function (state) {
        createMainGrid(this, false, state);
    };
}

// grid view page 정보 - 내가 구독한 언론사 (관찰자)
class gridViewSub extends gridViewInfo {
    // 구독한 언론사 리스트가 변경될 경우 뷰 업데이트
    update = function (state) {
        this.data = state;
        if (this.getCurrentPage() > this.getMaxPage() && this.getMaxPage() >= 0) {
            this.setPageNum(this.getMaxPage());
        }
        createMainGrid(this, false, state);
    };

    setPageNum = function (page_num) {
        this.current_page = page_num;
    };
}
```

4. 관찰자를 구독한다.
```
_sub_press_list.subscribe(this);
```
