### ISSUE TITLE
[FEATURE] 리스트 보기 UI

### ISSUE THREAD

**Issue by ori5r2** [ori5r2/fe-newsstand#2]
## Description
리스트 보기의 UI 구성 및 동작 

## Todo
- [x] 리스트뷰 (전체 언론사 / 내가 구독한 언론사) UI
  - [x] 내가 구독한 언론사 화살표 이벤트
  - [x] 내가 구독한 언론사 프로그레스바
- [x] 카테고리 hover : 밑줄 (이미 선택한 카테고리 제외)
- [x] 메인 뉴스 hover : 썸네일 이미지 5% 확대, 뉴스 타이틀 밑줄
- [x] 서브 뉴스 타이틀 hover : 밑줄
- [x] 새로고침하면 뉴스 랜덤
- [x] 구독하기 버튼 click :  스낵바 5초간 유지 후, 내가 구독한 언론사 탭의 리스트 보기 화면으로 이동
  - [x] 스낵바 UI 구현

## ETC
기타 고민 사항 및 힘들었던 점
