### ISSUE TITLE
[FEATURE] 리스트 보기 -내가 구독한 언론사 카테고리 탭

### ISSUE THREAD

**Issue by ori5r2** [ori5r2/fe-newsstand#4]
## Description
리스트 보기(내가 구독한 언론사)에서 카테고리 추가 기능

## Todo
- [x] 네비게이션 bar : 가로 탭에 언론사 이름 + 화살표 아이콘
- [x] 네비게이션 bar 가로 영역 넘어가는 경우 : 가로 스크롤
- [x] 언론사 순서는 구독한 순서대로 배치
- [ ] 내가 구독한 언론사 탭 : 리스트 보기가 기본

## ETC
기타 고민 사항 및 힘들었던 점
