### ISSUE TITLE
[REFACTOR]

### ISSUE THREAD

**Issue by ori5r2** [ori5r2/fe-newsstand#8]
## Todo
- [ ] css 파일 분리
- [ ] 비슷한 코드 함수로 처리
- [ ] mode(그리드, 리스트, 전체, 구독) 옵저버 패턴 적용
- [ ] public function 주석 추가

## ETC
기타 고민 사항 및 힘들었던 점
